
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry password;
	private global::Gtk.Label label2;
	private global::Gtk.Label label1;
	private global::Gtk.Entry usuario;
	private global::Gtk.Button salir;
	private global::Gtk.Button acepta;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.password = new global::Gtk.Entry ();
		this.password.CanFocus = true;
		this.password.Name = "password";
		this.password.IsEditable = true;
		this.password.InvisibleChar = '●';
		this.fixed1.Add (this.password);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.password]));
		w1.X = 107;
		w1.Y = 163;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w2.X = 157;
		w2.Y = 134;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuario");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w3.X = 161;
		w3.Y = 56;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.usuario = new global::Gtk.Entry ();
		this.usuario.CanFocus = true;
		this.usuario.Name = "usuario";
		this.usuario.IsEditable = true;
		this.usuario.InvisibleChar = '●';
		this.fixed1.Add (this.usuario);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.usuario]));
		w4.X = 104;
		w4.Y = 88;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.salir = new global::Gtk.Button ();
		this.salir.CanFocus = true;
		this.salir.Name = "salir";
		this.salir.UseUnderline = true;
		this.salir.BorderWidth = ((uint)(6));
		this.salir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
		this.fixed1.Add (this.salir);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.salir]));
		w5.X = 120;
		w5.Y = 244;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.acepta = new global::Gtk.Button ();
		this.acepta.CanFocus = true;
		this.acepta.Name = "acepta";
		this.acepta.UseUnderline = true;
		this.acepta.BorderWidth = ((uint)(6));
		this.acepta.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
		this.fixed1.Add (this.acepta);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.acepta]));
		w6.X = 197;
		w6.Y = 242;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.salir.Clicked += new global::System.EventHandler (this.OnSalirClicked);
		this.acepta.Clicked += new global::System.EventHandler (this.OnAceptaClicked);
	}
}
